navbar added
ilmhub-uz/oj.fe pull request #18
Opened 2022-02-24 12:28 UTC by diyorbek013

closes: #1

2022-02-26 13:01 UTC, Abubakr0904 commented
@diyorbek013 aka skrinshot yo'q. Kodizni olib, run qilib ko'rish ozgina qiyinroqda menga, shunga iltimos, skrinshot'lar joylang pull requestga. 

Har bir page ga o'tyaptimi, tez o'tyaptimi, huni ham tekshirib ko'ring. 

Merge conflictni o'zim hal qilib qo'ydim.

2022-02-26 13:02 UTC, Abubakr0904 requested changes
Shularni qilib bo'lganizdan keyin, run qilib skrinshot olib tashlab berolasizmi aka.

2022-02-26 18:23 UTC, diyorbek013 commented
![image](https://user-images.githubusercontent.com/91950041/155854642-b3f63939-cae4-49b5-8455-a2a4549c1db0.png)
![image](https://user-images.githubusercontent.com/91950041/155854655-44c9076c-acee-4702-9722-51985a304da2.png)
![image](https://user-images.githubusercontent.com/91950041/155854663-2a6efa84-4a6e-42fc-8e2a-d01bf4920eb2.png)
![image](https://user-images.githubusercontent.com/91950041/155854673-f79be5cd-58ac-4542-8827-34bd8414a168.png)
![image](https://user-images.githubusercontent.com/91950041/155854696-55a0a2bf-aae8-44b6-b857-800314e4fd61.png)
![image](https://user-images.githubusercontent.com/91950041/155854702-b7ce3df5-15bb-45b2-990a-3e22a2646019.png)
![image](https://user-images.githubusercontent.com/91950041/155854714-861dcf16-5fbf-4237-93e4-94d0cfc6b8ef.png)
![image](https://user-images.githubusercontent.com/91950041/155854725-d73edf75-9f3d-48c1-b985-08dfe92cf246.png)
![image](https://user-images.githubusercontent.com/91950041/155854735-59f90978-c005-4f15-be55-70c39f641a82.png)
![image](https://user-images.githubusercontent.com/91950041/155854740-c95a31ef-1b13-47d2-8b5b-dbf75f92f521.png)
![image](https://user-images.githubusercontent.com/91950041/155854747-f7eda0e8-a2b5-4160-879c-b6f1de98dffd.png)
mana aka rasmlar

2022-02-27 03:52 UTC, Abubakr0904 commented
@diyorbek013 aka. Login va register buttonlarni orasini sal ochib qo'ying. Keyin responsive'ligini ham ko'rsating. Telefon razmerda skrin qilib tashlang.

2022-02-28 19:24 UTC, Abubakr0904 commented
![Screenshot from 2022-03-01 00-22-44](https://user-images.githubusercontent.com/78490345/156045506-bc3eabf1-d98a-43f1-885b-8d4e100b545a.png)
![Screenshot from 2022-03-01 00-22-22](https://user-images.githubusercontent.com/78490345/156045520-4959253c-68ba-404a-b8eb-2c3f6e565a1a.png)
@wahid-d ustoz shuni ham merge qilib yuboring, iltimos.

2022-03-01 03:08 UTC, merged