Jamol/Umar/issue 4
ilmhub-uz/oj.fe pull request #30
Opened 2022-02-25 13:34 UTC by JamolDev1

closes #4 
<img width="960" alt="Login" src="https://user-images.githubusercontent.com/88763869/155724048-a01c3b46-78cb-4609-af36-eb2b461356a7.png">
<img width="960" alt="Register" src="https://user-images.githubusercontent.com/88763869/155724086-3af82ec0-dd09-4e3c-86ec-9f8756465ea7.png">

2022-02-25 23:55 UTC, Abubakr0904 requested changes
Hamma aytilgan muammochalarni resolve qilganizdan keyin qayta push piling va meni commentda @Abubakr0904 deb belgilab, bu haqida xabar bering. Yangi pull request qilishiz shart bo'lmaydi.

2022-02-25 23:55 UTC, Abubakr0904 commented on oj.fe.csproj
> +    <PackageReference Include="Radzen.Blazor" Version="3.15.6" />
Shu 12-qatorni olib tashlang. Chunki endi ishlatilmayapti Radzen package'i

2022-02-25 23:55 UTC, Abubakr0904 commented on Shared/RegisterModalComponent.razor
> +﻿@using System.ComponentModel.DataAnnotations
Bu file'ni tag tugi bilan Components papkaga o'tkazing. Shared'da turmasligi kerak.
RegisterComponent.razor bo'lsin nomi.

2022-02-25 23:55 UTC, Abubakr0904 commented on Shared/LoginModalComponent.razor
> +@using System.ComponentModel.DataAnnotations
Bu file'ni tag tugi bilan Components papkaga o'tkazing. Shared'da turmasligi kerak.
LoginComponent.razor bo'lsin nomi.

2022-02-26 12:14 UTC, JamolDev1 commented
@Abubakr0904  Etgan ishlarizi qb qoydim etganizdek Login va registerni nomini ozgartirib Components popkaga otqazib qoydinm

2022-02-26 13:12 UTC, Abubakr0904 approved these changes

2022-02-26 16:33 UTC, wahid-d commented
@Abubakr0904  @JamolDev1 Button juda katta, o'rtada kichikina bo'lib tursin. `col-lg-3 col-md-4` bo'lsa shunda yaxshi bo'ladi

2022-02-27 03:54 UTC, Abubakr0904 commented on oj.fe.csproj
> +    <PackageReference Include="newtonsoft.json" Version="13.0.1" />
Bu bilan ishlash osonroqda. Hech qanchamas ustoz kichkina package.@wahid-d

2022-02-28 19:38 UTC, Abubakr0904 commented
![Screenshot from 2022-03-01 00-37-09](https://user-images.githubusercontent.com/78490345/156047345-a8f47cf0-1642-4af9-ab7b-eacf3fc8ca68.png)
![Screenshot from 2022-03-01 00-37-00](https://user-images.githubusercontent.com/78490345/156047350-fdaf2f8e-a31d-482d-98b3-8baa90000b21.png)
@wahid-d ustoz, buni ham merge qilib bering  iltimos.

2022-03-02 05:15 UTC, closed without merging